services:
  postgres:
    image: postgres:15-alpine
    container_name: mini-ledger-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mini_ledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mini-ledger

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mini-ledger-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - '5672:5672' # AMQP port
      - '15672:15672' # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mini-ledger

  # Optional: PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mini-ledger-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - mini-ledger

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  mini-ledger:
    driver: bridge
