@baseUrl = http://localhost:3000
@accountId = d280b3e4-6a63-4d00-a769-921adea15ec8
@accountId2 = 77ff3a33-a024-4a01-b0e8-0ea45012cedd

### Create movement [CREDIT]
# @name createMovement
POST {{baseUrl}}/v1/movements
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "amount": 100,
  "type": "CREDIT",
  "description": "Compra no mercado"
}

### Create movement [DEBIT]
# @name createMovement
POST {{baseUrl}}/v1/movements
Content-Type: application/json

{
  "accountId": "{{accountId2}}",
  "amount": 100,
  "type": "DEBIT",
  "description": "Venda no mercado"
}

### Get account balance
GET {{baseUrl}}/v1/accounts/{{accountId}}/balance