@baseUrl = http://localhost:3000
@accountId = 1f43d96c-ebde-4ae2-bbd5-4696fa7aab10

### Create movement [CREDIT]
# @name createMovement
POST {{baseUrl}}/v1/movements
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "amount": 100,
  "type": "CREDIT",
  "description": "Compra no mercado"
}

### Create movement [DEBIT]
# @name createMovement
POST {{baseUrl}}/v1/movements
Content-Type: application/json

{
  "accountId": "{{accountId}}",
  "amount": 500,
  "type": "DEBIT",
  "description": "Venda no mercado"
}

### Get account balance
GET {{baseUrl}}/v1/accounts/{{accountId}}/balance